# Generated by Django 5.0.6 on 2024-05-24 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnero', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='fecha_created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
