# Generated by Django 5.0.6 on 2024-05-26 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnero', '0004_usuario_is_admin_usuario_last_login_usuario_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='telefono',
            field=models.CharField(default='351 888 9999', max_length=255),
            preserve_default=False,
        ),
    ]
